spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service
  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
management:
  tracing:
    sampling:
      probability: 1.0
keycloak:
  auth-server-url: http://localhost:9098
  realm: micro-service
  client-id: microservice-auth
  client-secret: AFzl9Z8apD0ggbcjilxEWWHMbARF1NIS

  # Endpoints
  token-uri: ${keycloak.auth-server-url}/realms/micro-service/protocol/openid-connect/token
  logout-uri: ${keycloak.auth-server-url}/realms/micro-service/protocol/openid-connect/logout
  admin-uri: ${keycloak.auth-server-url}/admin/realms/micro-service